//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMinds.WebService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int OptionId { get; set; }
        public string OptionValue { get; set; }
        public bool IsCorrect { get; set; }
        public int QuestionId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
