//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMinds.WebService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Options = new HashSet<Option>();
        }
    
        public int QuestionId { get; set; }
        public string Query { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid UpdatedBy { get; set; }
        public int TagId { get; set; }
    
        public virtual ICollection<Option> Options { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
