//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMinds.WebService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int TagId { get; set; }
        public string TagName { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.Guid UpdatedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
